use crate::graph::Graph;
pub use add::AddLayer;
use ark_bn254::Fr;
pub use cast::CastLayer;
pub use ceil::CeilLayer;
pub use concat::ConcatLayer;
pub use constantofshape::ConstOfShapeLayer;
pub use div::DivLayer;
pub use equal::EqualLayer;
pub use erf::ErfLayer;
pub use expand::ExpandLayer;
pub use gather::GatherLayer;
pub use lstm::LSTMLayer;
pub use matmul::MatMulLayer;
pub use mul::MulLayer;
use ndarray::ArrayD;
pub use pow::PowLayer;
pub use r#where::WhereLayer;
pub use range::RangeLayer;
pub use reducemean::ReduceMeanLayer;
pub use relu::ReLULayer;
pub use reshape::ReshapeLayer;
pub use scatternd::ScatterNDLayer;
pub use shape::ShapeLayer;
pub use slice::SliceLayer;
pub use softmax::SoftmaxLayer;
pub use split::SplitLayer;
pub use sqrt::SqrtLayer;
pub use squeeze::{SqueezeLayer, UnsqueezeLayer};
pub use sub::SubLayer;
use tract_onnx::pb::AttributeProto;
pub use transpose::TransposeLayer;

pub mod add;
pub mod cast;
pub mod ceil;
pub mod concat;
pub mod constantofshape;
pub mod div;
pub mod equal;
pub mod erf;
pub mod expand;
pub mod gather;
pub mod lstm;
pub mod matmul;
pub mod mul;
pub mod pow;
pub mod range;
pub mod reducemean;
pub mod relu;
pub mod reshape;
pub mod scatternd;
pub mod shape;
pub mod slice;
pub mod softmax;
pub mod split;
pub mod sqrt;
pub mod squeeze;
pub mod sub;
pub mod transpose;
pub mod r#where;

pub trait Layer {
  fn graph(input_shapes: &Vec<&Vec<usize>>, constants: &Vec<Option<&ArrayD<Fr>>>, attributes: &Vec<&AttributeProto>) -> (Graph, Vec<Vec<usize>>);
}
