use crate::graph::Graph;
pub use arithmetic::{AddLayer, SubLayer};
use ark_bn254::Fr;
pub use cast::CastLayer;
pub use concat::ConcatLayer;
pub use constantofshape::ConstOfShapeLayer;
pub use conv::ConvLayer;
pub use div::DivLayer;
pub use equal::EqualLayer;
pub use expand::ExpandLayer;
pub use gather::GatherLayer;
pub use lstm::LSTMLayer;
pub use matmul::MatMulLayer;
pub use mul::MulLayer;
use ndarray::ArrayD;
pub use nonlinear::*;
pub use pow::PowLayer;
pub use r#where::WhereLayer;
pub use range::RangeLayer;
pub use reducemean::ReduceMeanLayer;
pub use reshape::ReshapeLayer;
pub use scatternd::ScatterNDLayer;
pub use shape::ShapeLayer;
pub use slice::SliceLayer;
pub use softmax::SoftmaxLayer;
pub use split::SplitLayer;
pub use squeeze::{SqueezeLayer, UnsqueezeLayer};
use tract_onnx::pb::AttributeProto;
pub use transpose::TransposeLayer;

pub mod arithmetic;
pub mod cast;
pub mod concat;
pub mod constantofshape;
pub mod conv;
pub mod div;
pub mod equal;
pub mod expand;
pub mod gather;
pub mod lstm;
pub mod matmul;
pub mod mul;
pub mod nonlinear;
pub mod pow;
pub mod range;
pub mod reducemean;
pub mod reshape;
pub mod scatternd;
pub mod shape;
pub mod slice;
pub mod softmax;
pub mod split;
pub mod squeeze;
pub mod transpose;
pub mod r#where;

pub trait Layer {
  fn graph(input_shapes: &Vec<&Vec<usize>>, constants: &Vec<Option<&ArrayD<Fr>>>, attributes: &Vec<&AttributeProto>) -> (Graph, Vec<Vec<usize>>);
}
